services:
  - type: web
    name: mysteries-in-motion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mim-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
databases:
  - name: mim-db
    plan: free
