"""Added location column to Rehearsal model

Revision ID: 9d183af036f5
Revises: c414f8e8ec3f
Create Date: 2025-02-14 23:36:41.198569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d183af036f5'
down_revision = 'c414f8e8ec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rehearsal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rehearsal', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
