"""Add profile fields to User model

Revision ID: b752c2249579
Revises: d290cf6662dd
Create Date: 2025-02-13 23:28:44.266606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b752c2249579'
down_revision = 'd290cf6662dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('headshot_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('headshot_path')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
