"""Add calendar models

Revision ID: c414f8e8ec3f
Revises: bae7d34758e2
Create Date: 2025-02-14 00:50:34.388403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c414f8e8ec3f'
down_revision = 'bae7d34758e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('attendees', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehearsal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_date_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['show_date_id'], ['show_date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehearsal_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rehearsal_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rehearsal_id'], ['rehearsal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rehearsal_availability')
    op.drop_table('rehearsal')
    op.drop_table('show_date')
    # ### end Alembic commands ###
